dbt_lessons_new:
  outputs:
    dev:
      dataset: dags_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: civic-brand-422816-j0
      threads: 60
      type: bigquery
  target: dev
